
CREATE TABLE USUARIOS (
ID_USUARIO INT NULL PRIMARY KEY,
Nombre NVARCHAR(MAX),
Apellido NVARCHAR(MAX),
EMAIL NVARCHAR(MAX),
NOMBRE_USUARIO NVARCHAR(MAX),
CONTRASENA NVARCHAR(MAX),
ROL NVARCHAR(MAX)
);

CREATE TABLE ESTADOS (
ID_ESTADO INT NULL PRIMARY KEY,
NOMBRE NVARCHAR(MAX)
);

CREATE TABLE DOMICILIOS (
ID_DOMICILIO INT NULL PRIMARY KEY,
NOMBRE_DOMICILIO NVARCHAR(MAX),
ID_USUARIO INT
);

CREATE TABLE UBICACIONES (
ID_UBICACION INT NULL PRIMARY KEY,
NOMBRE NVARCHAR(MAX),
ID_DOMICILIO INT
);

CREATE TABLE DISPOSITIVOS (
ID_DISPOSITIVO INT NULL PRIMARY KEY,
NOMBRE_DISPOSITIVO NVARCHAR(MAX),
TIPO_DISPOSITIVO NVARCHAR(MAX),
ESTADO_DISPOSITIVO INT,
ID_UBICACION INT
);

CREATE TABLE AUTOMATIZACIONES (
ID_AUTOMATIZACION INT NULL PRIMARY KEY,
NOMBRE_AUTOMATIZACION NVARCHAR(MAX),
DESCRIPCION_AUTOMATIZACION NVARCHAR(MAX),
ID_USUARIO INT NULL
);

CREATE TABLE AUTOMATIZACIONES_DISPOSITIVOS (
ID_AUTOMATIZACION INT,
ID_DISPOSITIVO INT,
ESTADO_DESEADO INT
);

INSERT INTO ESTADOS (ID_ESTADO, NOMBRE) VALUES (1, N'encendido');
INSERT INTO ESTADOS (ID_ESTADO, NOMBRE) VALUES (2, N'apagado');
